export default {
    BLACK: 'SFProDisplay-Black',
    BLACK_ITALIC: 'SFProDisplay-BlackItalic',
    BOLD: 'SFProDisplay-Bold',
    BOLD_ITALIC: 'SFProDisplay-BoldItalic',
    HEAVY: 'SFProDisplay-Heavy',
    HEAVY_ITALIC: 'SFProDisplay-HeavyItalic',
    LIGHT: 'SFProDisplay-Light',
    LIGHT_ITALIC: 'SFProDisplay-LightItalic',
    MEDIUM: 'SFProDisplay-Medium',
    MEDIUM_ITALIC: 'SFProDisplay-MediumItalic',
    REGULAR: 'SFProDisplay-Regular',
    REGULAR_ITALIC: 'SFProDisplay-RegularItalic',
    SEMIBOLD: 'SFProDisplay-Semibold',
    SEMIBOLD_ITALIC: 'SFProDisplay-SemiboldItalic',
    THIN: 'SFProDisplay-Thin',
    THIN_ITALIC: 'SFProDisplay-ThinItalic',
    ULTRALIGHT: 'SFProDisplay-Ultralight',
    ULTRALIGHT_ITALIC: 'SFProDisplay-Ultralight',
}